### ISSUE TITLE
SEC-2730: Provide an order higher than LOWEST_PRECEDENCE for springSecurityFilterChain that's created by WebSecurityConfiguration

### ISSUE THREAD

**Issue by rwinch** [rwinch/spring-security-migrate-issues#2747]
[Andy Wilkinson](https://jira.spring.io/secure/ViewProfile.jspa?name=awilkinson) (Migrated from [SEC-2730](https://jira.spring.io/browse/SEC-2730)) said:

The `springSecurityFilterChain` bean that's created by `WebSecurityConfiguration` is unordered. This means that it's considered to have the default order provided by `AnnotationAwareOrderComparator` which is `LOWEST_PRECEDENCE`. This makes the filter go last (or joint last if there are other `LOWEST_PRECEDENCE` filters configured) when a request is being processed. In a Spring Boot application this makes it difficult for a user to configure their own filter which should run after Spring Security's filter.

**Comment by walec51** [comment]
+1 for `0`

**Comment by rwinch** [comment]
This was handled in Spring Boot 1.3 https://github.com/spring-projects/spring-boot/blob/v1.3.8.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/SecurityFilterAutoConfiguration.java#L66
